### ISSUE TITLE
Nether Crash from Pigman ticking entity

### ISSUE THREAD

**Issue by gh0st31337** [The-Nexus-Project/Limitless#28]
I am creating a new issue for this because this is still happening in 1.0.8.a.  I have attached two crash reports from my server.

[crash-2020-01-05_20.14.42-server.txt](https://github.com/The-Nexus-Project/Limitless/files/4024370/crash-2020-01-05_20.14.42-server.txt)
[crash-2020-01-05_20.30.07-server.txt](https://github.com/The-Nexus-Project/Limitless/files/4024371/crash-2020-01-05_20.30.07-server.txt)

**Comment by dotParx** [comment]
Not sure if your experience lines up...
I was experiencing this from many mobs.
I was using Eye of the Nebula (15% chance to teleport away form any attacker)
It tended to happen most while I was in combat... especially with a bow while I was holding the drawstring... making me the ticking entity most likely.

Since I removed this item I have crashed the server 0 times... still testing however.

**Comment by gh0st31337** [comment]
The last time it crashed for me I literally just can through the portal and
it crashed. My server logs always said it was the zombie pigmen too. Maybe
it has something to do with them fighting those clan guys, or whatever they
are called.

**Comment by Gbergz** [comment]
Re-open if further discussion is needed.
